import {
  levi,
  tgb,
  zeros,
  asoken,
  sangtraan,
  iloda,
  vuive,
  llstylish,
  theanh,
  bauffs,
  music_img,
  sport_img,
} from "../Assets/Images";

import { vidList4, vidList5 } from "./videoData";

export const channelList = [
  {
    id: 1,
    name: "Levi",
    img: levi,
    tag: "@levi97",
    subs: 349000,
    desc: "Kênh Youtube chính thức của Levi - Đỗ Duy Khánh. Đăng ký kênh để cập nhật những video mới nhất của Levi.",
    subbed: true,
    vids: 123,
  },
  {
    id: 2,
    name: "Thầy Giáo Ba",
    img: tgb,
    tag: "@thaygiaoba6325",
    subs: 337000,
    desc: "Kênh tấu hài của cựu game thủ chuyên nghiệp kiêm hlv bù nhìn Ba Rọi Béo aka Thầy Giáo Ba",
    subbed: true,
    vids: 123,
  },
  {
    id: 3,
    name: "iLoda",
    img: iloda,
    tag: "@iLoda",
    subs: 195000,
    desc: "",
    subbed: true,
    vids: 123,
  },
  {
    id: 4,
    name: "LL Stylish",
    img: llstylish,
    tag: "@LLStylish",
    subs: 873000,
    desc: "",
    subbed: true,
    vids: 123,
  },
  {
    id: 5,
    name: "sangtraan",
    img: sangtraan,
    tag: "@sangtraan",
    subs: 445000,
    desc: "Chào, mình là Sang. Mình stream. Nghe mình nói nhảm vào lúc 9h tối hàng ngày trừ Chủ Nhật. Email for business: chickengang.business@gmail.com",
    subbed: true,
    vids: 123,
  },
  {
    id: 6,
    name: "TheAnh69",
    img: theanh,
    tag: "@theanh690",
    subs: 445000,
    desc: "Minh livestream vào 18h thứ 2,4,5,7 vô cùng chăm chỉ. Anh em đừng quên like và bật chuộng thông báo nhé.",
    subbed: true,
    vids: 123,
  },
  {
    id: 7,
    name: "Thebausffs",
    img: bauffs,
    tag: "@Thebausffs",
    subs: 841000,
    desc: "Hey guys it's me Thebausffs EUW challenger OTP full AD Sion. You can find me everyday on my twitch channel http://www.twitch.tv/thebausffs Twitter : twitter.com/thebausffs Discord : discord.gg/thebausffs",
    subbed: true,
    vids: 123,
  },
  {
    id: 8,
    name: "Vui vẻ",
    img: vuive,
    tag: "",
    subs: 841000,
    desc: "Mọi thứ cũng đơn giản thôi ------------------------------------------------------------------------------------------------------ 🔥HỢP TÁC MỜI LIÊN HỆ: Mobile: Mr. Nguyễn Văn Linh Zalo (nhanh nhất) và SĐT: 0363948598 Email: work.thereviewer@gmail.com For Chinese Buisness:contactvuive@163.com",
    subbed: true,
    vids: 177,
  },
  {
    id: 9,
    name: "Zeros",
    img: zeros,
    tag: "@mazuong2k",
    subs: 242000,
    desc: "Kênh chính thức của Zeros",
    subbed: true,
    vids: 177,
  },
  {
    id: 10,
    name: "Asoken",
    img: asoken,
    tag: "@asoken98",
    subs: 51700,
    desc: "I LOVE JAX",
    subbed: true,
    vids: 177,
  },
];

export const ytbMusicChannel = {
  id: 1,
  name: "Âm nhạc",
  thumb: music_img,
  subs: 121000000,
  subbed: true,
  vidList: vidList4,
};

export const ytbSportChannel = {
  id: 2,
  name: "Thể thao",
  thumb: sport_img,
  subs: 74800000,
  subbed: false,
  vidList: vidList5,
};
